# Generated by Django 4.1.2 on 2022-11-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bienenkonigin_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beehive_number', models.IntegerField(default=1)),
                ('zeichen_konigin', models.IntegerField(default=1)),
                ('eiablage_seit', models.DateField(verbose_name='egg laying start date')),
                ('konigin_rasse', models.CharField(max_length=20)),
                ('konigin_linie', models.CharField(max_length=20)),
                ('muttervolk', models.CharField(max_length=20)),
                ('drohnenvölker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_fixing_values', models.DateTimeField(verbose_name='date and time of fixing weather values')),
                ('air_temperature_sensor', models.IntegerField(default=0)),
                ('air_temperature_api', models.IntegerField(default=0)),
                ('air_humidity_sensor', models.IntegerField(default=0)),
                ('air_humidity_api', models.IntegerField(default=0)),
                ('atmospheric_pressure_api', models.IntegerField(default=0)),
                ('wind_power_api', models.IntegerField(default=0)),
                ('wind_direction_api', models.CharField(max_length=20)),
                ('weather_description_api', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weight_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_weight_fixation', models.DateTimeField(verbose_name='date and time of weighing')),
                ('weight_beehive', models.IntegerField(default=1)),
                ('beehive_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scales_apiary.bienenkonigin_1')),
            ],
        ),
    ]
