# Generated by Django 4.1.2 on 2022-11-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienenkonigin_1',
            old_name='drohnenvölker',
            new_name='drohnenvolker',
        ),
    ]
