# Generated by Django 4.1.2 on 2022-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0002_rename_drohnenvölker_bienenkonigin_1_drohnenvolker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_3',
            name='air_temperature_sensor',
            field=models.SmallIntegerField(default=0),
        ),
    ]
