# Generated by Django 4.1.2 on 2022-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0003_alter_weather_3_air_temperature_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_3',
            name='air_humidity_api',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='air_humidity_sensor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='air_temperature_api',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='atmospheric_pressure_api',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='wind_power_api',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
