# Generated by Django 4.1.2 on 2022-11-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0004_alter_weather_3_air_humidity_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienenkonigin_1',
            name='beehive_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bienenkonigin_1',
            name='zeichen_konigin',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weight_2',
            name='weight_beehive',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
