# Generated by Django 4.1.2 on 2023-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0008_alter_weather_3_wind_direction_ico_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_3',
            name='weather_description_ico_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
