# Generated by Django 4.1.2 on 2023-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0009_weather_3_weather_description_ico_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_3',
            name='wind_gust_api',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
