# Generated by Django 4.1.2 on 2023-03-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0011_alter_weather_3_wind_power_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_3',
            name='daytime_api',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
