# Generated by Django 4.1.2 on 2023-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0013_alter_bienenkonigin_1_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_3',
            name='air_humidity_api',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ф(API, %)'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='air_humidity_sensor',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='ф(%)'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='air_temperature_api',
            field=models.SmallIntegerField(null=True, verbose_name='t(API, °C)'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='air_temperature_sensor',
            field=models.SmallIntegerField(null=True, verbose_name='t(°C)'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='atmospheric_pressure_api',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='p(API)'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='daytime_api',
            field=models.CharField(blank=True, max_length=1, verbose_name='D/N'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='weather_description_api',
            field=models.CharField(blank=True, max_length=100, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='wind_direction_api',
            field=models.CharField(blank=True, max_length=20, verbose_name='напр'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='wind_gust_api',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='порывы'),
        ),
        migrations.AlterField(
            model_name='weather_3',
            name='wind_power_api',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='ветер'),
        ),
    ]
