# Generated by Django 4.1.2 on 2023-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales_apiary', '0014_alter_weather_3_air_humidity_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_3',
            name='wind_direction_api',
            field=models.CharField(blank=True, max_length=20, verbose_name='направление ветра'),
        ),
    ]
